apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: josehuipipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: josehuipipelinesjavascriptdocker 
    spec:
      containers:
        - name: josehuipipelinesjavascriptdocker 
          image: chhuicontainerregistry.azurecr.io/josehuipipelinesjavascriptdocker
          ports:
          - containerPort: 8080